apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
    spec:
      containers:
        - name: webapi
          image: you_docker_hub_name/webapi:latest